version: '3.8'
services:
  shipxplorer:
    image: ghcr.io/sdr-enthusiasts/vesselalert
    container_name: vesselalert
    hostname: vesselalert
    restart: always
    environment:
      - AIS_URL=http://my.ais-catcher/website
      - CHECK_INTERVAL=30
      - VESSELDBFILE=/data/vessel.db
      - VESSELDBLOCK=/run/vesseldb.lock
      - MIN_MSG_COUNT=5
      - MAX_MSG_AGE=86400
      - MASTODON_SERVER=airwaves.social
      - MASTODON_ACCESS_TOKEN=my_mastodon_token
      - MASTODON_SKIP_FILTER
      - MASTODON_MIN_DISTANCE=
      - MASTODON_POST_VISIBILITY=public
      - MASTODON_LINK_SHIPXPLORER=on
      - MASTODON_LINK_MARINETRAFFIC=on
      - MASTODON_LINK_VESSELFINDER=on
    tmpfs:
      - /tmp
      - /run
    volumes:
      - /opt/ais/data:/data
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
